package mona.joyhentai.model;

public class Books {

    @Override
    public String toString() {
        return "Books{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", code='" + code + '\'' +
                ", pages=" + pages +
                ", createTime=" + createTime +
                ", status=" + status +
                ", src='" + src + '\'' +
                ", tag='" + tag + '\'' +
                ", writer='" + writer + '\'' +
                ", language='" + language + '\'' +
                ", type='" + type + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.id
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.name
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.code
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.pages
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    private Integer pages;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.create_time
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.status
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.src
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    private String src;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.tag
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.writer
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    private String writer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.language
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.type
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.id
     *
     * @return the value of books.id
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.id
     *
     * @param id the value for books.id
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.name
     *
     * @return the value of books.name
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.name
     *
     * @param name the value for books.name
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.code
     *
     * @return the value of books.code
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.code
     *
     * @param code the value for books.code
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.pages
     *
     * @return the value of books.pages
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    public Integer getPages() {
        return pages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.pages
     *
     * @param pages the value for books.pages
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    public void setPages(Integer pages) {
        this.pages = pages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.create_time
     *
     * @return the value of books.create_time
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.create_time
     *
     * @param createTime the value for books.create_time
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.status
     *
     * @return the value of books.status
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.status
     *
     * @param status the value for books.status
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.src
     *
     * @return the value of books.src
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.src
     *
     * @param src the value for books.src
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    public void setSrc(String src) {
        this.src = src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.tag
     *
     * @return the value of books.tag
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.tag
     *
     * @param tag the value for books.tag
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.writer
     *
     * @return the value of books.writer
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    public String getWriter() {
        return writer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.writer
     *
     * @param writer the value for books.writer
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    public void setWriter(String writer) {
        this.writer = writer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.language
     *
     * @return the value of books.language
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.language
     *
     * @param language the value for books.language
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.type
     *
     * @return the value of books.type
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.type
     *
     * @param type the value for books.type
     *
     * @mbggenerated Tue Oct 19 10:01:26 CST 2021
     */
    public void setType(String type) {
        this.type = type;
    }
}