package mona.joyhentai.model;

public class BooksPages {
    @Override
    public String toString() {
        return "BooksPages{" +
                "id=" + id +
                ", bookId=" + bookId +
                ", name='" + name + '\'' +
                ", suffix='" + suffix + '\'' +
                ", page=" + page +
                ", status=" + status +
                ", url='" + url + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books_pages.id
     *
     * @mbggenerated Mon Oct 11 22:48:32 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books_pages.book_id
     *
     * @mbggenerated Mon Oct 11 22:48:32 CST 2021
     */
    private Integer bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books_pages.name
     *
     * @mbggenerated Mon Oct 11 22:48:32 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books_pages.suffix
     *
     * @mbggenerated Mon Oct 11 22:48:32 CST 2021
     */
    private String suffix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books_pages.page
     *
     * @mbggenerated Mon Oct 11 22:48:32 CST 2021
     */
    private Integer page;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books_pages.status
     *
     * @mbggenerated Mon Oct 11 22:48:32 CST 2021
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books_pages.url
     *
     * @mbggenerated Mon Oct 11 22:48:32 CST 2021
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books_pages.id
     *
     * @return the value of books_pages.id
     *
     * @mbggenerated Mon Oct 11 22:48:32 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books_pages.id
     *
     * @param id the value for books_pages.id
     *
     * @mbggenerated Mon Oct 11 22:48:32 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books_pages.book_id
     *
     * @return the value of books_pages.book_id
     *
     * @mbggenerated Mon Oct 11 22:48:32 CST 2021
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books_pages.book_id
     *
     * @param bookId the value for books_pages.book_id
     *
     * @mbggenerated Mon Oct 11 22:48:32 CST 2021
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books_pages.name
     *
     * @return the value of books_pages.name
     *
     * @mbggenerated Mon Oct 11 22:48:32 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books_pages.name
     *
     * @param name the value for books_pages.name
     *
     * @mbggenerated Mon Oct 11 22:48:32 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books_pages.suffix
     *
     * @return the value of books_pages.suffix
     *
     * @mbggenerated Mon Oct 11 22:48:32 CST 2021
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books_pages.suffix
     *
     * @param suffix the value for books_pages.suffix
     *
     * @mbggenerated Mon Oct 11 22:48:32 CST 2021
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books_pages.page
     *
     * @return the value of books_pages.page
     *
     * @mbggenerated Mon Oct 11 22:48:32 CST 2021
     */
    public Integer getPage() {
        return page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books_pages.page
     *
     * @param page the value for books_pages.page
     *
     * @mbggenerated Mon Oct 11 22:48:32 CST 2021
     */
    public void setPage(Integer page) {
        this.page = page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books_pages.status
     *
     * @return the value of books_pages.status
     *
     * @mbggenerated Mon Oct 11 22:48:32 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books_pages.status
     *
     * @param status the value for books_pages.status
     *
     * @mbggenerated Mon Oct 11 22:48:32 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books_pages.url
     *
     * @return the value of books_pages.url
     *
     * @mbggenerated Mon Oct 11 22:48:32 CST 2021
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books_pages.url
     *
     * @param url the value for books_pages.url
     *
     * @mbggenerated Mon Oct 11 22:48:32 CST 2021
     */
    public void setUrl(String url) {
        this.url = url;
    }
}