package mona.joyhentai.model;

public class BooksRepeat {

    @Override
    public String toString() {
        return "BooksRepeat{" +
                "id=" + id +
                ", bookId=" + bookId +
                ", bookName='" + bookName + '\'' +
                ", idArr='" + idArr + '\'' +
                ", pagesArr='" + pagesArr + '\'' +
                ", codeArr='" + codeArr + '\'' +
                ", repeatCount='" + repeatCount + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books_repeat.id
     *
     * @mbggenerated Mon Oct 11 22:37:01 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books_repeat.book_id
     *
     * @mbggenerated Mon Oct 11 22:37:01 CST 2021
     */
    private Integer bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books_repeat.book_name
     *
     * @mbggenerated Mon Oct 11 22:37:01 CST 2021
     */
    private String bookName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books_repeat.id_arr
     *
     * @mbggenerated Mon Oct 11 22:37:01 CST 2021
     */
    private String idArr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books_repeat.pages_arr
     *
     * @mbggenerated Mon Oct 11 22:37:01 CST 2021
     */
    private String pagesArr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books_repeat.code_arr
     *
     * @mbggenerated Mon Oct 11 22:37:01 CST 2021
     */
    private String codeArr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books_repeat.repeat_count
     *
     * @mbggenerated Mon Oct 11 22:37:01 CST 2021
     */
    private String repeatCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books_repeat.id
     *
     * @return the value of books_repeat.id
     *
     * @mbggenerated Mon Oct 11 22:37:01 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books_repeat.id
     *
     * @param id the value for books_repeat.id
     *
     * @mbggenerated Mon Oct 11 22:37:01 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books_repeat.book_id
     *
     * @return the value of books_repeat.book_id
     *
     * @mbggenerated Mon Oct 11 22:37:01 CST 2021
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books_repeat.book_id
     *
     * @param bookId the value for books_repeat.book_id
     *
     * @mbggenerated Mon Oct 11 22:37:01 CST 2021
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books_repeat.book_name
     *
     * @return the value of books_repeat.book_name
     *
     * @mbggenerated Mon Oct 11 22:37:01 CST 2021
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books_repeat.book_name
     *
     * @param bookName the value for books_repeat.book_name
     *
     * @mbggenerated Mon Oct 11 22:37:01 CST 2021
     */
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books_repeat.id_arr
     *
     * @return the value of books_repeat.id_arr
     *
     * @mbggenerated Mon Oct 11 22:37:01 CST 2021
     */
    public String getIdArr() {
        return idArr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books_repeat.id_arr
     *
     * @param idArr the value for books_repeat.id_arr
     *
     * @mbggenerated Mon Oct 11 22:37:01 CST 2021
     */
    public void setIdArr(String idArr) {
        this.idArr = idArr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books_repeat.pages_arr
     *
     * @return the value of books_repeat.pages_arr
     *
     * @mbggenerated Mon Oct 11 22:37:01 CST 2021
     */
    public String getPagesArr() {
        return pagesArr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books_repeat.pages_arr
     *
     * @param pagesArr the value for books_repeat.pages_arr
     *
     * @mbggenerated Mon Oct 11 22:37:01 CST 2021
     */
    public void setPagesArr(String pagesArr) {
        this.pagesArr = pagesArr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books_repeat.code_arr
     *
     * @return the value of books_repeat.code_arr
     *
     * @mbggenerated Mon Oct 11 22:37:01 CST 2021
     */
    public String getCodeArr() {
        return codeArr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books_repeat.code_arr
     *
     * @param codeArr the value for books_repeat.code_arr
     *
     * @mbggenerated Mon Oct 11 22:37:01 CST 2021
     */
    public void setCodeArr(String codeArr) {
        this.codeArr = codeArr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books_repeat.repeat_count
     *
     * @return the value of books_repeat.repeat_count
     *
     * @mbggenerated Mon Oct 11 22:37:01 CST 2021
     */
    public String getRepeatCount() {
        return repeatCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books_repeat.repeat_count
     *
     * @param repeatCount the value for books_repeat.repeat_count
     *
     * @mbggenerated Mon Oct 11 22:37:01 CST 2021
     */
    public void setRepeatCount(String repeatCount) {
        this.repeatCount = repeatCount;
    }
}