package mona.joyhentai.dao;

import mona.joyhentai.model.BooksRepeat;

import java.util.List;

public interface BooksRepeatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books_repeat
     *
     * @mbggenerated Mon Oct 11 22:37:01 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books_repeat
     *
     * @mbggenerated Mon Oct 11 22:37:01 CST 2021
     */
    int insert(BooksRepeat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books_repeat
     *
     * @mbggenerated Mon Oct 11 22:37:01 CST 2021
     */
    BooksRepeat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books_repeat
     *
     * @mbggenerated Mon Oct 11 22:37:01 CST 2021
     */
    List<BooksRepeat> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books_repeat
     *
     * @mbggenerated Mon Oct 11 22:37:01 CST 2021
     */
    int updateByPrimaryKey(BooksRepeat record);
}